### ISSUE TITLE
NuGet package restore.

### ISSUE THREAD

**Issue by f-gt** [kyeondiscord/DiscordLookup#1]
![image](https://user-images.githubusercontent.com/79057754/121103306-aecfa900-c7cd-11eb-90cc-93a1b6c7e2a6.png)
It says project.assets.json is not found and I have to run a NuGet package restore, i'm not sure how to do this, can you help me?
Thank you

**Comment by KyeOnDiscord** [comment]
> ![image](https://user-images.githubusercontent.com/79057754/121103306-aecfa900-c7cd-11eb-90cc-93a1b6c7e2a6.png)
> It says project.assets.json is not found and I have to run a NuGet package restore, i'm not sure how to do this, can you help me?
> Thank you

Just download it from releases [here](https://github.com/kyeondiscord/DiscordLookup/releases/download/1.0/DiscordLookup.exe)

If you want to compile it with the source code add the nuget package `Json.Net`
